WebServiceClients:
  PersonService:
    Id: 17297D66BE667121
    ServiceClass: performance.client.PersonServiceService
    WsdlUrl: http://localhost:8081/ivy/ws/designer/Performance/17297D0F7635769C?WSDL
    WsCallLibrary: CXF
    Endpoints:
      PersonServicePort:
      - '{ivy.app.baseurl}/ws/Performance/17297D0F7635769C'
